services:
  - type: web
    name: budget-buddy-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: budget-buddy-disk
      mountPath: /var/data
      sizeGB: 1